apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xwsylx74v-go 
  janus-idp.io/tekton: xwsylx74v-go
  backstage.io/kubernetes-id: xwsylx74v-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xwsylx74v-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml